# Generated by Django 4.0.1 on 2022-01-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('observed', models.CharField(max_length=100)),
                ('public', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('uuid', models.Field(primary_key=True, serialize=False)),
                ('date_name', models.CharField(max_length=100)),
                ('date_observed', models.CharField(max_length=100)),
            ],
        ),
    ]
