# Generated by Django 4.0.1 on 2022-01-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('observed', models.DateField()),
                ('public', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_name', models.CharField(max_length=100)),
                ('date_observed', models.CharField(max_length=100)),
            ],
        ),
    ]
