# Generated by Django 4.0.1 on 2022-01-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Holidays',
        ),
        migrations.AlterModelOptions(
            name='holidays',
            options={'verbose_name_plural': 'holidays'},
        ),
    ]
